/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CtrlOut.C
**     Project   : Switcher
**     Processor : MC9S08SH8CPJ
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.21, CPU db: 3.00.062
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 1/6/2016, 3:23 AM
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       11            |  PTC1_TPM1CH1_ADP9
**             ----------------------------------------------------
**
**         Port name                   : PTC
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTCD      [$0004]
**         Port control register       : PTCDD     [$0005]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool CtrlOut_GetVal(void);
**         PutVal - void CtrlOut_PutVal(bool Val);
**         ClrVal - void CtrlOut_ClrVal(void);
**         SetVal - void CtrlOut_SetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CtrlOut. */

#include "CtrlOut.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  CtrlOut_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool CtrlOut_GetVal(void)

**  This method is implemented as a macro. See CtrlOut.h file.  **
*/

/*
** ===================================================================
**     Method      :  CtrlOut_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void CtrlOut_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PTCD, 0x02);           /* PTCD1=0x01 */
  } else { /* !Val */
    clrReg8Bits(PTCD, 0x02);           /* PTCD1=0x00 */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  CtrlOut_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CtrlOut_ClrVal(void)

**  This method is implemented as a macro. See CtrlOut.h file.  **
*/

/*
** ===================================================================
**     Method      :  CtrlOut_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void CtrlOut_SetVal(void)

**  This method is implemented as a macro. See CtrlOut.h file.  **
*/


/* END CtrlOut. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
