/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : timer.C
**     Project   : Switcher
**     Processor : MC9S08SH8CPJ
**     Component : Init_RTC
**     Version   : Component 01.017, Driver 01.09, CPU db: 3.00.062
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 1/11/2016, 2:40 AM
**     Abstract  :
**          This file implements the API (RTC) module 
**          initialization according to the Peripheral Initialization 
**          Bean settings, and defines interrupt service routines prototypes.
**          The Autonomous periodical Interrupt module can generate
**          periodical interrupts independent of the clock source of 
**          the MCU. To enable the timer, the bit APIFE needs to be 
**          set. The API timer is either clocked by a trimmable 
**          internal RC oscillator or the bus clock. Timer operation
**          will freeze when MCU clock source is selected and bus clock 
**          is turned off. The clock source can be selected with bit
**          APICLK. As soon as the configured timeout period of the API 
**          has elapsed, the APIF bit is set. An interrupt, indicated by 
**          flag APIF = 1, is triggered if interrupt enable bit APIE = 1.
**     Settings  :
**          Bean name                                      : timer
**          Device                                         : RTC
**          Settings                                       : 
**            Clock settings                               : 
**              Clock select                               : Internal clock and first set of prescalers
**              Prescaler                                  : 256
**              RTC modulo value                           : 122
**              Period                                     : 1.007616 s
**          Interrupts                                     : 
**            Interrupt                                    : Vrtc
**            RTC Interrupt                                : Enabled
**            ISR name                                     : TimeInt
**          Initialization                                 : 
**            NON_MCU_INIT                                 : 
**              Call Init method                           : yes
**     Contents  :
**         Init - void timer_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE timer. */

#include "timer.h"
extern long ticks;
extern byte blink;

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Switcher.c
**      Events.c
**
** ###################################################################
*/

      ISR(TimeInt)
      {
      // NOTE: The routine should include the following actions to obtain
      //       correct functionality of the hardware.
      //
      //       The RTIF bit must be set to 1 to clear the interrupt request.
      //       Example: RTCSC_RTIF = 1;
      
      ticks++;
      blink ^= 1;
      RTCSC_RTIF = 1;
      }


/*
** ===================================================================
**     Method      :  timer_Init (component Init_RTC)
**
**     Description :
**         This method initializes registers of the RTC module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void timer_Init(void)
{
  /* RTCMOD: RTCMOD=0x7A */
  setReg8(RTCMOD, 0x7A);               /* Set modulo register */ 
  /* RTCSC: RTIF=1,RTCLKS=2,RTIE=1,RTCPS=5 */
  setReg8(RTCSC, 0xD5);                /* Configure RTC */ 
}

/* END timer. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
