/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : timer.H
**     Project   : Switcher
**     Processor : MC9S08SH8CPJ
**     Component : Init_RTC
**     Version   : Component 01.017, Driver 01.09, CPU db: 3.00.062
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 1/8/2016, 3:25 AM
**     Abstract  :
**          This file implements the API (RTC) module 
**          initialization according to the Peripheral Initialization 
**          Bean settings, and defines interrupt service routines prototypes.
**          The Autonomous periodical Interrupt module can generate
**          periodical interrupts independent of the clock source of 
**          the MCU. To enable the timer, the bit APIFE needs to be 
**          set. The API timer is either clocked by a trimmable 
**          internal RC oscillator or the bus clock. Timer operation
**          will freeze when MCU clock source is selected and bus clock 
**          is turned off. The clock source can be selected with bit
**          APICLK. As soon as the configured timeout period of the API 
**          has elapsed, the APIF bit is set. An interrupt, indicated by 
**          flag APIF = 1, is triggered if interrupt enable bit APIE = 1.
**     Settings  :
**          Bean name                                      : timer
**          Device                                         : RTC
**          Settings                                       : 
**            Clock settings                               : 
**              Clock select                               : Internal clock and first set of prescalers
**              Prescaler                                  : 256
**              RTC modulo value                           : 122
**              Period                                     : 1.007616 s
**          Interrupts                                     : 
**            Interrupt                                    : Vrtc
**            RTC Interrupt                                : Enabled
**            ISR name                                     : TimeInt
**          Initialization                                 : 
**            NON_MCU_INIT                                 : 
**              Call Init method                           : yes
**     Contents  :
**         Init - void timer_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __timer
#define __timer

/* MODULE timer. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"




/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see timer.c file for more information).
** ===================================================================
*/
__interrupt void TimeInt(void);

void timer_Init(void);
/*
** ===================================================================
**     Method      :  timer_Init (component Init_RTC)
**
**     Description :
**         This method initializes registers of the RTC module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END timer. */

#endif
/* ifndef __timer */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
